#!/usr/bin/env python3
"""Build the GitHub Pages site under docs/ from the sample bundles.

For each bundle in samples/bundles/, renders a fresh self-contained visualizer
to docs/<bundle>.html, then writes docs/index.html linking them all. Enable
Pages in the repo (Settings -> Pages -> Deploy from branch: main, folder /docs)
and the sample knowledge graphs are browsable online, no clone required.

    python samples/build_pages.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
REPO = ROOT.parent
sys.path.insert(0, str(REPO))

from okfgen.consumer import load_bundle          # noqa: E402
from okfgen.visualize import render_html          # noqa: E402

BUNDLES = ROOT / "bundles"
DOCS = REPO / "docs"

# Human blurbs per sample (producer perspective from the OKF blog).
BLURBS = {
    "acme-sales": ("A database", "Datasets, tables, and column schemas — with "
                   "foreign-key join paths inferred by the enrichment agent."),
    "petclinic-api": ("A source system", "A code repository's structure, modules, "
                      "and dependencies."),
    "observability-docs": ("A documentation site", "Cross-linked documentation "
                           "pages as a navigable knowledge graph."),
    "toronto-beaches": ("A live public dataset", "Toronto Beaches Water Quality "
                        "(E. coli readings) from the Toronto Open Data CKAN portal."),
}


def main() -> int:
    if not BUNDLES.is_dir():
        print("No sample bundles found; run build_samples.py first.", file=sys.stderr)
        return 1
    DOCS.mkdir(exist_ok=True)

    cards = []
    for path in sorted(p for p in BUNDLES.iterdir() if p.is_dir()):
        name = path.name
        bundle = load_bundle(str(path))
        title = f"OKF — {name}"
        (DOCS / f"{name}.html").write_text(render_html(bundle, title=title), encoding="utf-8")
        kind, desc = BLURBS.get(name, ("A bundle", ""))
        cards.append((name, kind, desc, len(bundle.concepts)))
        print(f"rendered docs/{name}.html ({len(bundle.concepts)} concepts)")

    (DOCS / "index.html").write_text(_index_html(cards), encoding="utf-8")
    (DOCS / ".nojekyll").write_text("", encoding="utf-8")  # serve _-prefixed files verbatim
    print(f"wrote docs/index.html with {len(cards)} sample(s)")
    return 0


def _index_html(cards) -> str:
    items = "\n".join(
        f"""    <a class="card" href="./{name}.html">
      <div class="kind">{kind}</div>
      <h2>{name}</h2>
      <p>{desc}</p>
      <div class="meta">{n} concepts &middot; interactive graph &rarr;</div>
    </a>"""
        for name, kind, desc, n in cards
    )
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>okfgen — sample OKF bundles</title>
<style>
  :root {{ --bg:#0f1420; --panel:#171e2e; --line:#2a3450; --fg:#e6ebf5; --muted:#8b98b8; --accent:#5b9dff; }}
  * {{ box-sizing:border-box; }}
  body {{ margin:0; background:var(--bg); color:var(--fg);
    font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif; }}
  .wrap {{ max-width:920px; margin:0 auto; padding:48px 20px 80px; }}
  h1 {{ font-size:30px; margin:0 0 6px; }}
  .lead {{ color:var(--muted); margin:0 0 8px; }}
  .lead a {{ color:var(--accent); text-decoration:none; }}
  .grid {{ display:grid; grid-template-columns:repeat(auto-fill,minmax(260px,1fr)); gap:16px; margin-top:32px; }}
  .card {{ display:block; background:var(--panel); border:1px solid var(--line); border-radius:12px;
    padding:20px; text-decoration:none; color:inherit; transition:border-color .15s, transform .15s; }}
  .card:hover {{ border-color:var(--accent); transform:translateY(-2px); }}
  .kind {{ font-size:12px; text-transform:uppercase; letter-spacing:.05em; color:var(--accent); }}
  .card h2 {{ font-size:19px; margin:6px 0 8px; }}
  .card p {{ color:var(--muted); font-size:14px; margin:0 0 14px; }}
  .meta {{ font-size:12px; color:var(--muted); }}
  footer {{ margin-top:48px; color:var(--muted); font-size:14px; }}
  footer a {{ color:var(--accent); text-decoration:none; }}
</style>
</head>
<body>
  <div class="wrap">
    <h1>okfgen — sample knowledge graphs</h1>
    <p class="lead">Interactive visualizers for
      <a href="https://github.com/GoogleCloudPlatform/knowledge-catalog/blob/main/okf/SPEC.md">Open Knowledge Format</a>
      bundles, generated by
      <a href="https://github.com/bushans/okfgen">okfgen</a>.</p>
    <p class="lead">Each page is a single self-contained file — no backend, no tracking, data stays in your browser.</p>
    <div class="grid">
{items}
    </div>
    <footer>
      Produced deterministically from git repos, databases, docs sites, and live
      open-data portals. See the <a href="https://github.com/bushans/okfgen">repository</a> to run it on your own data.
    </footer>
  </div>
</body>
</html>
"""


if __name__ == "__main__":
    raise SystemExit(main())
